kind: Pod 
apiVersion: v1
metadata:
  name: environment
spec:
  containers:
  - name: nginx
    image: nginx 
    env:
     - name: cousre
       value: devops
     - name: trainer
       value: shiva
     - name: duration
       value: "120 hours"
