kind: Pod
apiVersion: v1
metadata: 
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: cousre
        valueFrom: 
          configMapKeyRef: 
             name: nginx-config
             key: course
      - name: duration
        valueFrom: 
          configMapKeyRef:
             name: nginx-config
             key: duration
